title: Manoa Marketplace
google_analytics:
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  is_project_page: true
  repository_url: https://github.com/manoamarketplace
gems:
  - jekyll-mentions
